export const SITE_URL = "https://groverconsult.com";
export const SITE_NAME = "Grover Consult";

export interface SolutionPage {
  slug: string;
  partnerName: string;
  logo: string;
  domain: string;
  category: string;
  headline: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  capabilities: string[];
  useCases: string[];
  industries: string[];
  faqs: { q: string; a: string }[];
}

export interface ServicePage {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  headline: string;
  intro: string;
  benefits: { title: string; description: string }[];
  deliverables: string[];
  faqs: { q: string; a: string }[];
}

export const solutionPages: SolutionPage[] = [
  {
    slug: "hyperverge",
    partnerName: "HyperVerge",
    logo: "hyperverge.svg",
    domain: "hyperverge.co",
    category: "Identity Verification & Digital Onboarding",
    headline: "HyperVerge Digital Identity & Onboarding Implementation",
    metaTitle: "HyperVerge Implementation Partner Philippines & Indonesia | Grover Consult",
    metaDescription: "Grover Consult is an authorized HyperVerge implementation partner for banks in the Philippines and Indonesia. Deploy AI-powered digital identity verification and paperless onboarding.",
    intro: "HyperVerge is a leading AI-powered identity verification and digital onboarding platform trusted by financial institutions across Southeast Asia. As an authorized implementation partner, Grover Consult deploys HyperVerge's OCR, liveness detection, and fraud-screening capabilities to help banks onboard customers digitally — reducing drop-off rates and accelerating KYC compliance.",
    capabilities: [
      "AI-powered ID document verification (passports, national IDs, driver's licenses)",
      "Liveness detection and anti-spoofing for remote KYC",
      "Automated OCR data extraction and validation",
      "Fraud risk scoring and watchlist screening",
      "End-to-end digital onboarding workflow integration",
      "BSP / OJK regulatory compliance support",
    ],
    useCases: [
      "Paperless bank account opening for retail and SME customers",
      "Remote KYC for digital lending and credit card issuance",
      "Agent-assisted onboarding at branch and kiosk channels",
      "Real-time fraud detection during customer acquisition",
    ],
    industries: ["Retail Banking", "Digital Banks (Neobanks)", "Consumer Finance", "Microfinance", "Insurance"],
    faqs: [
      { q: "What regulators does HyperVerge support in the Philippines?", a: "HyperVerge supports BSP (Bangko Sentral ng Pilipinas) e-KYC requirements, including AMLA-aligned identity verification workflows." },
      { q: "How long does a typical HyperVerge deployment take?", a: "With Grover Consult's implementation expertise, most banks complete a production-ready integration in 8–16 weeks depending on existing system complexity." },
      { q: "Can HyperVerge integrate with our existing core banking system?", a: "Yes. Grover Consult specialises in connecting HyperVerge to core banking platforms including TCS BaNCS, Temenos, and custom CBS environments via REST API." },
    ],
  },
  {
    slug: "intentai",
    partnerName: "INT:NT",
    logo: "intentai.svg",
    domain: "intentai.io",
    category: "Agentic AI Platform",
    headline: "INT:NT Agentic AI Platform for Banking & Finance",
    metaTitle: "INT:NT AI Native Platform Implementation for Banks | Grover Consult",
    metaDescription: "Deploy INT:NT's agentic AI platform for banking with Grover Consult. Build intelligent automation, AI agents, and LLM-powered workflows for BFSI operations in Southeast Asia.",
    intro: "INT:NT is an AI-native platform for building agentic systems — autonomous AI workflows that reason, plan, and execute complex multi-step processes. Grover Consult helps BFSI organisations deploy INT:NT to automate credit decisioning, regulatory reporting, customer service, and back-office operations, dramatically reducing manual processing time.",
    capabilities: [
      "Agentic workflow orchestration for multi-step banking processes",
      "LLM-powered document analysis and extraction",
      "AI-driven credit analysis and underwriting support",
      "Regulatory report generation and validation",
      "Intelligent customer service automation",
      "Integration with existing banking data lakes and CRM systems",
    ],
    useCases: [
      "Automated loan underwriting and credit memo generation",
      "AI-assisted regulatory filing and compliance monitoring",
      "Intelligent document processing for trade finance",
      "Customer inquiry resolution with AI agents",
    ],
    industries: ["Universal Banks", "Investment Banks", "Insurance", "Asset Management", "Regulatory Bodies"],
    faqs: [
      { q: "What makes INT:NT different from standard RPA solutions?", a: "Unlike RPA, INT:NT's agentic architecture can handle unstructured inputs, make decisions based on context, and adapt to process variations — making it far more robust for complex banking workflows." },
      { q: "Is INT:NT compliant with data residency requirements in the Philippines and Indonesia?", a: "Grover Consult configures INT:NT deployments to meet local data sovereignty requirements, including on-premise and private cloud options." },
    ],
  },
  {
    slug: "posidex",
    partnerName: "Posidex",
    logo: "posidex.svg",
    domain: "posidex.com",
    category: "PII Data Vault & Entity Resolution",
    headline: "Posidex PII Data Vault & Master Data Management for Banks",
    metaTitle: "Posidex Data Vault Implementation Partner Philippines | Grover Consult",
    metaDescription: "Grover Consult deploys Posidex PII data vault and entity resolution for Philippine and Indonesian banks — securing sensitive customer data while enabling enterprise-wide customer intelligence.",
    intro: "Posidex provides a secure PII Data Vault and enterprise-grade entity resolution platform, enabling financial institutions to create a unified customer master record across all banking channels and systems. Grover Consult implements Posidex to eliminate duplicate customer records, strengthen data governance, and achieve a true single customer view.",
    capabilities: [
      "Encrypted PII data vault with tokenisation",
      "Probabilistic and deterministic entity matching",
      "Duplicate detection and customer deduplication",
      "Single Customer View (SCV) data hub",
      "AML/CFT watchlist and adverse media screening",
      "Data lineage and audit trail management",
    ],
    useCases: [
      "Creating a Golden Customer Record across all product systems",
      "Detecting shell companies and related-party fraud",
      "Cross-selling enabled by unified customer profile",
      "GDPR and Data Privacy Act compliance for customer data",
    ],
    industries: ["Universal Banks", "Rural Banks", "Savings Banks", "Insurance", "Government Financial Institutions"],
    faqs: [
      { q: "How does Posidex handle the Philippine Data Privacy Act (DPA) requirements?", a: "Posidex's vault architecture supports DPA-compliant data minimisation, purpose limitation, and subject access request (SAR) workflows. Grover Consult ensures the implementation meets NPC guidelines." },
      { q: "Can Posidex handle the scale of a large Philippine universal bank?", a: "Yes. Posidex is designed for enterprise scale and handles hundreds of millions of records with sub-second matching — proven in large BFSI deployments across Asia." },
    ],
  },
  {
    slug: "tcs-bancs",
    partnerName: "TCS BaNCS",
    logo: "tcsbancs.svg",
    domain: "tcs.com",
    category: "Core Banking & Payments",
    headline: "TCS BaNCS Core Banking Implementation in Southeast Asia",
    metaTitle: "TCS BaNCS Implementation Partner Philippines & Indonesia | Grover Consult",
    metaDescription: "Grover Consult is a TCS BaNCS implementation partner for Philippine and Indonesian banks — delivering core banking transformation, digital channel integration, and payments modernisation.",
    intro: "TCS BaNCS is the world's most widely deployed core banking platform, powering over 400 financial institutions globally. As a TCS BaNCS implementation partner, Grover Consult delivers full-lifecycle CBS transformation engagements — from requirements design and data migration through to go-live support and hypercare — for banks in the Philippines and Indonesia.",
    capabilities: [
      "Core banking replacement and upgrade programmes",
      "CASA, loans, trade finance, and treasury module implementation",
      "Payments hub and real-time payment scheme integration (InstaPay, PESONet, BI-FAST)",
      "Digital channel and mobile banking integration",
      "Legacy data migration and parallel run management",
      "Post-go-live optimisation and change management",
    ],
    useCases: [
      "Greenfield core banking deployment for new digital banks",
      "Legacy CBS replacement for established commercial banks",
      "Payments modernisation for instant payment scheme participation",
      "Rural bank consolidation and system standardisation",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Rural Banks", "Thrift Banks", "Digital Banks"],
    faqs: [
      { q: "How long does a TCS BaNCS implementation typically take?", a: "For mid-sized banks, a full core banking replacement typically takes 18–36 months. Grover Consult's delivery methodology focuses on phased go-lives to reduce risk and accelerate time-to-value." },
      { q: "Does Grover Consult handle BSP/OJK regulatory reporting post-implementation?", a: "Yes. Our team ensures TCS BaNCS is configured to generate all required regulatory reports for BSP (Philippines) and OJK (Indonesia), including CISA, AML STRs, and prudential returns." },
      { q: "What is the difference between TCS BaNCS and other core banking systems?", a: "TCS BaNCS offers a highly componentised, API-first architecture that is well-suited to the composable banking trend. Its depth in Philippine banking regulations is stronger than many competitors." },
    ],
  },
  {
    slug: "puresoftware",
    partnerName: "PureSoftware",
    logo: "puresoftware.svg",
    domain: "puresoftware.com",
    category: "Lending & Digital Wallet Solutions",
    headline: "PureSoftware Lending & Wallet Platform Implementation",
    metaTitle: "PureSoftware Lending & Wallet Implementation Philippines | Grover Consult",
    metaDescription: "Deploy PureSoftware's lending and digital wallet platform in the Philippines and Indonesia with Grover Consult — accelerating digital credit and e-wallet product launches for banks and fintechs.",
    intro: "PureSoftware delivers a modern lending origination platform and digital wallet solution purpose-built for BFSI. Grover Consult implements PureSoftware's loan lifecycle management and e-wallet capabilities, enabling banks and financial institutions to rapidly launch digital credit products and wallet services to their retail and SME customer base.",
    capabilities: [
      "End-to-end digital loan origination (retail, SME, and microfinance)",
      "Credit scoring engine integration and bureau connectivity",
      "Digital wallet issuance and transaction management",
      "Regulatory compliance workflows (BSP, OJK)",
      "Collections and delinquency management",
      "Embedded finance API for fintech partnerships",
    ],
    useCases: [
      "Bank-led digital lending product launch",
      "SME credit platform for underserved segments",
      "Digital wallet and stored value facility (SVF) deployment",
      "Microfinance digitisation and loan automation",
    ],
    industries: ["Commercial Banks", "Rural Banks", "Microfinance Institutions", "Fintechs", "Cooperatives"],
    faqs: [
      { q: "Can PureSoftware integrate with our existing credit bureau (CIBI/NFIS)?", a: "Yes. Grover Consult integrates PureSoftware with Philippine credit bureaus (CIBI, TransUnion Philippines) and Indonesian bureaus (SLIK OJK, Pefindo) as part of the standard implementation." },
      { q: "What is the typical time to launch a new digital lending product?", a: "With PureSoftware's pre-built modules and Grover Consult's implementation accelerators, banks can launch a digital lending product in 3–6 months." },
    ],
  },
  {
    slug: "perforce",
    partnerName: "Perforce",
    logo: "perforce.svg",
    domain: "perforce.com",
    category: "DevOps & Software Quality",
    headline: "Perforce DevOps Solutions for Banking & Financial Services",
    metaTitle: "Perforce DevOps Implementation for Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult deploys Perforce DevOps, version control, and software testing solutions for Philippine and Indonesian banks — accelerating secure software delivery and compliance.",
    intro: "Perforce provides enterprise DevOps tooling including version control (Helix Core), automated testing (Helix QAC, Perfecto), and project management. For banks undergoing digital transformation, Perforce's toolchain enables secure, compliant software delivery at scale. Grover Consult implements Perforce solutions to help banking IT teams increase delivery velocity while maintaining regulatory compliance and code quality standards.",
    capabilities: [
      "Helix Core enterprise version control for large-scale banking systems",
      "Automated static code analysis for security and compliance",
      "Test automation and continuous testing frameworks",
      "DevSecOps pipeline integration",
      "Audit trail and change management for BSP/OJK IT governance",
      "Agile project planning and release management",
    ],
    useCases: [
      "Enterprise source code management for multi-team banking projects",
      "Automated compliance testing for core banking changes",
      "DevOps maturity improvement for bank IT divisions",
      "Secure CI/CD pipeline implementation for digital banking apps",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Insurance", "Investment Firms", "Payment Companies"],
    faqs: [
      { q: "How does Perforce help banks meet BSP IT governance requirements?", a: "Perforce Helix Core provides immutable audit trails, access controls, and change history required by BSP's Technology Risk Management guidelines. Grover Consult configures these controls as part of every deployment." },
      { q: "Can Perforce integrate with existing JIRA and Confluence setups?", a: "Yes. Perforce integrates natively with Atlassian tools, Jenkins, GitLab, and other common banking DevOps toolchains." },
    ],
  },
  {
    slug: "kyriba",
    partnerName: "Kyriba",
    logo: "kyriba.svg",
    domain: "kyriba.com",
    category: "Treasury & Liquidity Management",
    headline: "Kyriba Treasury & Liquidity Management for Southeast Asian Banks",
    metaTitle: "Kyriba Treasury Management Implementation Philippines | Grover Consult",
    metaDescription: "Deploy Kyriba treasury and liquidity management with Grover Consult for Philippine and Indonesian banks — modernising cash management, FX, and investment portfolio operations.",
    intro: "Kyriba is the global leader in cloud treasury and liquidity management, trusted by over 2,500 financial institutions and corporations worldwide. Grover Consult implements Kyriba for banks and corporates in the Philippines and Indonesia, enabling real-time cash visibility, FX risk management, and automated payment processing to replace manual spreadsheet-based treasury operations.",
    capabilities: [
      "Real-time cash position and liquidity management",
      "FX exposure and hedging workflow automation",
      "Bank connectivity and payment processing (SWIFT, local payment rails)",
      "Investment portfolio management and accounting",
      "Counterparty risk and credit limit monitoring",
      "Treasury accounting and regulatory reporting",
    ],
    useCases: [
      "Corporate treasury transformation from spreadsheet to cloud",
      "Bank-side liquidity optimisation and intraday cash management",
      "FX risk management for banks with multi-currency books",
      "Payment factory centralisation across group entities",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Development Finance Institutions", "Large Corporates", "Government-Owned Banks"],
    faqs: [
      { q: "Is Kyriba available as an on-premise deployment for Philippine banks with data residency requirements?", a: "Kyriba is primarily a SaaS platform. Grover Consult works with your compliance team to ensure that Kyriba's cloud architecture meets BSP data residency guidelines through appropriate data classification and contractual controls." },
      { q: "How long does a Kyriba treasury implementation take?", a: "A standard Kyriba implementation for a mid-size bank or corporate takes 12–20 weeks with Grover Consult's accelerated delivery methodology." },
    ],
  },
  {
    slug: "moneythor",
    partnerName: "Moneythor",
    logo: "moneythor.svg",
    domain: "moneythor.com",
    category: "Personalised Banking Experiences",
    headline: "Moneythor Personalised Digital Banking Implementation",
    metaTitle: "Moneythor Personalisation Engine for Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult deploys Moneythor's personalisation and customer engagement engine for banks in the Philippines and Indonesia — driving digital banking app engagement, financial wellness, and revenue growth.",
    intro: "Moneythor is a leading digital banking personalisation platform that uses transaction data and AI to deliver hyper-relevant customer experiences — including spending insights, savings nudges, offers, and financial wellness features. Grover Consult integrates Moneythor into banks' mobile and internet banking channels, helping financial institutions compete with neobanks on customer engagement.",
    capabilities: [
      "Transaction data enrichment and categorisation",
      "Personalised financial insights and spending analytics",
      "Savings goals, budgeting, and financial wellness tools",
      "AI-driven next-best-action and offer personalisation",
      "Loyalty and rewards programme integration",
      "White-label PFM (Personal Finance Management) module",
    ],
    useCases: [
      "Increasing mobile banking app engagement and daily active users",
      "Cross-selling savings and investment products through contextual nudges",
      "Financial wellness programmes for retail banking customers",
      "Competing against neobanks with data-driven personalisation",
    ],
    industries: ["Retail Banks", "Digital Banks (Neobanks)", "Savings Banks", "Thrift Banks", "Credit Unions"],
    faqs: [
      { q: "Does Moneythor require a full core banking system replacement?", a: "No. Moneythor operates as a middleware layer that connects to your existing transaction data via API — making it deployable without a full CBS transformation." },
      { q: "How quickly can we see results from a Moneythor deployment?", a: "Grover Consult has delivered Moneythor integrations in as little as 12 weeks. Measurable improvements in app engagement are typically visible within 60–90 days post-launch." },
    ],
  },
  {
    slug: "finartis",
    partnerName: "Finartis",
    logo: "finartis.svg",
    domain: "finartis.com",
    category: "Wealth Management Solutions",
    headline: "Finartis Wealth Management Platform for Banks & Wealth Managers",
    metaTitle: "Finartis Wealth Management Implementation Southeast Asia | Grover Consult",
    metaDescription: "Deploy Finartis wealth management and portfolio administration with Grover Consult for banks and wealth managers in the Philippines and Indonesia — powering next-generation advisory services.",
    intro: "Finartis provides a comprehensive wealth management platform covering portfolio management, client reporting, compliance, and digital advisory — purpose-built for private banks, wealth managers, and fund administrators. Grover Consult implements Finartis to help financial institutions in Southeast Asia launch or scale their wealth management business with a modern, integrated platform.",
    capabilities: [
      "Portfolio management and asset allocation modelling",
      "Client 360 and relationship management (CRM integration)",
      "Regulatory-compliant client reporting and factsheets",
      "Securities master data and pricing management",
      "Robo-advisory and digital onboarding for investment products",
      "Fund accounting and NAV calculation",
    ],
    useCases: [
      "Launching a private banking or wealth management division",
      "Replacing legacy portfolio management systems",
      "Enabling digital investment advisory for mass-affluent clients",
      "Unit investment trust fund (UITF) administration",
    ],
    industries: ["Private Banks", "Universal Banks (Wealth Divisions)", "Trust Companies", "Asset Managers", "Family Offices"],
    faqs: [
      { q: "Can Finartis support BSP-regulated wealth products like UITFs?", a: "Yes. Grover Consult configures Finartis to support BSP-regulated trust and investment products, including UITF accounting, prospectus management, and BSP reporting requirements." },
      { q: "Does Finartis support multi-currency portfolios for clients with offshore assets?", a: "Yes. Finartis is designed for multi-currency, multi-asset class portfolio management, supporting FX-denominated securities, offshore holdings, and consolidated reporting." },
    ],
  },
  {
    slug: "apix",
    partnerName: "Apix",
    logo: "apix.svg",
    domain: "apixplatform.com",
    category: "API Marketplace & Open Banking",
    headline: "Apix Open Banking & API Marketplace Implementation",
    metaTitle: "Apix Open Banking Platform Implementation Philippines | Grover Consult",
    metaDescription: "Grover Consult implements Apix open banking API marketplace for Philippine and Indonesian banks — enabling fintech partnerships, API monetisation, and regulatory open banking compliance.",
    intro: "Apix is the ASEAN region's leading open banking API marketplace, enabling banks to expose and consume APIs for fintech partnerships, product innovation, and regulatory open finance compliance. Grover Consult helps banks deploy Apix to build their fintech ecosystem, launch banking-as-a-service (BaaS) propositions, and comply with BSP and OJK open banking mandates.",
    capabilities: [
      "API gateway and developer portal deployment",
      "Pre-built bank API catalogue (account, payments, product, identity)",
      "Fintech partner onboarding and API key management",
      "Open finance regulatory compliance (BSP Open Finance, OJK SNAP)",
      "API analytics and monetisation framework",
      "Sandbox environment for third-party developer testing",
    ],
    useCases: [
      "Launching a bank-run fintech API marketplace",
      "Complying with BSP Open Finance Framework requirements",
      "Enabling embedded banking partnerships with e-commerce and payroll platforms",
      "Accelerating new product development through third-party APIs",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Digital Banks", "Rural Banks", "Payment Service Providers"],
    faqs: [
      { q: "Is Apix compliant with the BSP Open Finance Framework (Circular 1153)?", a: "Yes. Apix was built with the ASEAN regulatory landscape in mind. Grover Consult ensures the deployment aligns with BSP Circular 1153 open finance data portability requirements." },
      { q: "How does Apix differ from building a custom API gateway?", a: "Apix provides a pre-built, bank-grade API marketplace with security, developer portal, and marketplace features built in — saving 12–18 months of custom development time versus building from scratch." },
    ],
  },
  {
    slug: "yappes",
    partnerName: "Yappes",
    logo: "yappes.svg",
    domain: "yappes.com",
    category: "API Management & Integration",
    headline: "Yappes API Management System for Financial Institutions",
    metaTitle: "Yappes API Management Implementation Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult deploys Yappes API management platform for banks in the Philippines and Indonesia — enabling enterprise API governance, lifecycle management, and secure third-party integration.",
    intro: "Yappes is an enterprise API management platform that enables financial institutions to design, publish, secure, and monitor APIs across their ecosystem. Grover Consult implements Yappes to help banks establish robust API governance frameworks, accelerating digital integration with fintechs, payment schemes, and internal systems.",
    capabilities: [
      "Full API lifecycle management (design, test, publish, retire)",
      "API gateway with authentication, throttling, and quota management",
      "Developer portal and API documentation hub",
      "API analytics and usage monitoring dashboards",
      "Enterprise integration with ESB and microservices architectures",
      "API security testing and vulnerability management",
    ],
    useCases: [
      "Establishing an enterprise API governance framework",
      "Centralising bank API exposure for fintech and partner channels",
      "Migrating from monolithic to microservices-based architecture",
      "Regulatory API reporting and audit trail management",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Insurance Companies", "Payment Companies", "Microfinance Institutions"],
    faqs: [
      { q: "How does Yappes handle high-transaction-volume environments like Philippine banks?", a: "Yappes is designed for high-throughput environments, supporting horizontal scaling and low-latency API management. Grover Consult tunes the deployment for your specific transaction volumes." },
    ],
  },
  {
    slug: "fable",
    partnerName: "Fable",
    logo: "fable.svg",
    domain: "fable.co",
    category: "Digital Lending Platform",
    headline: "Fable Digital Lending Platform for Banks & Microfinance",
    metaTitle: "Fable Digital Lending Implementation Philippines Indonesia | Grover Consult",
    metaDescription: "Grover Consult implements Fable's digital lending platform for Philippine and Indonesian banks and microfinance institutions — automating loan origination, decisioning, and collections.",
    intro: "Fable is a modern digital lending platform that automates the full loan lifecycle — from digital application and credit bureau checks through decisioning, disbursement, and collections — enabling financial institutions to launch and scale digital credit products rapidly. Grover Consult deploys Fable to help banks and MFIs reduce lending costs and reach underserved borrowers.",
    capabilities: [
      "Digital loan application with e-KYC and digital onboarding",
      "Automated credit decisioning with configurable scorecards",
      "Credit bureau and alternative data integration",
      "Loan disbursement via digital wallets and bank accounts",
      "Collections workflow and delinquency management",
      "Product configurator for multiple loan types (personal, SME, agricultural)",
    ],
    useCases: [
      "Salary loan and consumer credit digitalisation",
      "SME working capital lending with automated decisioning",
      "Agricultural finance for rural banks and cooperatives",
      "Buy-now-pay-later (BNPL) lending infrastructure",
    ],
    industries: ["Commercial Banks", "Rural Banks", "Microfinance Institutions", "Cooperatives", "Fintechs"],
    faqs: [
      { q: "Can Fable connect to Philippine credit bureaus like CIBI and TransUnion?", a: "Yes. Grover Consult configures Fable's bureau integration to connect with all major Philippine credit bureaus as well as alternative data sources for thin-file borrowers." },
      { q: "How does Fable handle the credit decisioning for agricultural loans with non-standard income?", a: "Fable supports custom scorecard configuration that can incorporate non-traditional income signals — crop harvest cycles, cooperative membership, land titles — tailored to agricultural lending." },
    ],
  },
  {
    slug: "midships",
    partnerName: "Midships",
    logo: "midships.svg",
    domain: "midships.io",
    category: "Cybersecurity & Infrastructure Security",
    headline: "Midships Cybersecurity Platform for Banking Infrastructure",
    metaTitle: "Midships Cybersecurity Implementation for Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult deploys Midships cybersecurity defence platforms for Philippine and Indonesian banks — protecting critical banking infrastructure against advanced threats and regulatory cyber requirements.",
    intro: "Midships provides enterprise cybersecurity solutions focused on protecting critical financial infrastructure from advanced persistent threats, insider risks, and operational technology (OT) vulnerabilities. Grover Consult implements Midships to help banks meet BSP and OJK cybersecurity framework requirements while fortifying their most critical systems.",
    capabilities: [
      "Critical infrastructure security monitoring and threat detection",
      "Zero-trust network architecture implementation",
      "SIEM/SOC deployment and security operations support",
      "Penetration testing and red team exercises",
      "Incident response planning and tabletop exercises",
      "Regulatory cybersecurity compliance assessment (BSP, OJK)",
    ],
    useCases: [
      "Protecting core banking and payment switch infrastructure",
      "Meeting BSP Technology Risk Management cybersecurity requirements",
      "Building a bank-grade Security Operations Centre (SOC)",
      "Supply chain risk assessment for banking technology vendors",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Payment Companies", "Central Banks", "Financial Market Infrastructures"],
    faqs: [
      { q: "How does Midships help banks comply with BSP Circular 982 (Technology Risk Management)?", a: "Grover Consult's Midships implementation covers the key cyber domains in BSP Circular 982 — including threat detection, access management, incident response, and business continuity — providing a compliance evidence pack for BSP examination." },
    ],
  },
  {
    slug: "flagright",
    partnerName: "Flagright",
    logo: "flagright.svg",
    domain: "flagright.com",
    category: "Financial Crime & AML Compliance",
    headline: "Flagright AI-Powered AML & Financial Crime Compliance",
    metaTitle: "Flagright AML Compliance Implementation for Banks Philippines | Grover Consult",
    metaDescription: "Deploy Flagright AI-powered AML transaction monitoring and financial crime compliance with Grover Consult for Philippine and Indonesian banks — reducing false positives and meeting AMLC requirements.",
    intro: "Flagright is a next-generation financial crime compliance platform powered by AI — replacing rule-based AML systems with machine learning-driven transaction monitoring, sanctions screening, and risk scoring. Grover Consult implements Flagright to help banks in the Philippines and Indonesia reduce AML false-positive rates, lower compliance costs, and strengthen their AMLA/AMLC reporting obligations.",
    capabilities: [
      "AI-powered transaction monitoring with adaptive rule learning",
      "Real-time sanctions screening (UN, OFAC, EU, local lists)",
      "Customer risk rating and segmentation",
      "Suspicious transaction report (STR) case management",
      "PEP (Politically Exposed Persons) screening",
      "Regulatory reporting to AMLC (Philippines) and PPATK (Indonesia)",
    ],
    useCases: [
      "Replacing legacy AML platforms with AI-driven monitoring",
      "Reducing AML alert false-positive rates by 40–80%",
      "Meeting AMLC and FATF compliance requirements",
      "Real-time sanctions screening for cross-border payments",
    ],
    industries: ["Commercial Banks", "Rural Banks", "Money Transfer Operators", "Digital Banks", "Payment Companies"],
    faqs: [
      { q: "Does Flagright meet AMLC reporting requirements in the Philippines?", a: "Yes. Grover Consult configures Flagright's STR generation workflows to comply with AMLC Regulatory Issuance No. 1 Series of 2021 and subsequent amendments." },
      { q: "How does Flagright's AI reduce false positives compared to rule-based systems?", a: "Flagright's ML models learn from your institution's specific transaction patterns and analyst feedback over time, continually refining alert thresholds to reduce noise while maintaining detection sensitivity." },
    ],
  },
  {
    slug: "zafin",
    partnerName: "Zafin",
    logo: "zafin.svg",
    domain: "zafin.com",
    category: "Banking Monetisation & Fee Management",
    headline: "Zafin Banking Monetisation & Pricing Platform",
    metaTitle: "Zafin Pricing & Fee Management Implementation for Banks | Grover Consult",
    metaDescription: "Grover Consult implements Zafin's banking monetisation and product pricing platform for Philippine and Indonesian banks — enabling dynamic pricing, bundled product management, and revenue optimisation.",
    intro: "Zafin is the leading banking monetisation platform, enabling financial institutions to design, price, and manage complex product bundles, fee schedules, and relationship-based pricing — independent of their core banking system. Grover Consult deploys Zafin to help banks modernise their product and pricing capabilities without replacing their core banking infrastructure.",
    capabilities: [
      "Product catalogue and bundle management",
      "Relationship-based pricing and tiered fee schedules",
      "Dynamic pricing and promotional offer management",
      "Bilateral contract and pricing agreement management",
      "Revenue analytics and pricing performance dashboard",
      "Core banking system decoupling for pricing flexibility",
    ],
    useCases: [
      "Launching complex bundled product propositions (relationship banking packages)",
      "Implementing loyalty-based fee waivers and relationship pricing",
      "Separating product pricing from legacy core banking constraints",
      "Pricing innovation for SME banking and transaction banking clients",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Transaction Banks", "Corporate Banks", "Development Finance Institutions"],
    faqs: [
      { q: "Can Zafin work alongside our existing TCS BaNCS or Temenos core banking system?", a: "Yes. Zafin is designed as a product layer that sits on top of any core banking system, including TCS BaNCS and Temenos T24. Grover Consult handles the bi-directional integration." },
    ],
  },
  {
    slug: "seclore",
    partnerName: "Seclore",
    logo: "seclore.svg",
    domain: "seclore.com",
    category: "Data Security & Rights Management",
    headline: "Seclore Data Security & Digital Rights Management for Banks",
    metaTitle: "Seclore Data Security Implementation for Banks Philippines | Grover Consult",
    metaDescription: "Deploy Seclore data-centric security and digital rights management with Grover Consult for Philippine and Indonesian banks — protecting sensitive documents and data wherever they travel.",
    intro: "Seclore provides data-centric security — embedding persistent protection directly into documents and files so that sensitive banking data remains secure regardless of where it is shared, stored, or accessed. Grover Consult implements Seclore to help banks protect customer data, financial reports, and regulatory documents from unauthorised access, data leakage, and insider threats.",
    capabilities: [
      "Automatic document classification and policy-based protection",
      "Persistent file-level encryption following documents across systems",
      "Granular access control (view, edit, print, copy, forward permissions)",
      "Real-time access monitoring and revocation",
      "Integration with Microsoft 365, SharePoint, and banking document management systems",
      "Data Privacy Act compliance evidence and audit trail",
    ],
    useCases: [
      "Protecting sensitive credit reports shared with third parties",
      "Securing board and ALCO documents from leakage",
      "Controlling access to customer PII in shared banking systems",
      "Compliance with Philippine Data Privacy Act (DPA) and Indonesian PDP Law",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Insurance", "Asset Management", "Government Financial Institutions"],
    faqs: [
      { q: "Does Seclore integrate with Microsoft 365 environments common in Philippine banks?", a: "Yes. Seclore natively integrates with Microsoft 365, including Outlook, SharePoint, and Teams. Grover Consult handles the Microsoft 365 integration as part of the standard deployment." },
      { q: "Can Seclore revoke access to a document that has already been shared externally?", a: "Yes. Seclore's persistent protection means access can be revoked instantly, even after a document has been shared outside the bank — a key control for data breach incident response." },
    ],
  },
  {
    slug: "geniusto",
    partnerName: "Geniusto",
    logo: "geniusto.svg",
    domain: "geniusto.com",
    category: "AI-Driven Automation & Intelligent Decisioning",
    headline: "Geniusto AI Automation & Intelligent Decisioning for Banking",
    metaTitle: "Geniusto AI Automation Platform for Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult implements Geniusto's AI-driven automation and intelligent decisioning platform for Philippine and Indonesian banks — automating back-office operations and credit decisions with AI.",
    intro: "Geniusto provides an AI-powered automation and intelligence platform that enables banks to automate complex decisioning, document processing, and operational workflows without extensive custom development. Grover Consult deploys Geniusto to help financial institutions reduce manual processing, accelerate straight-through processing (STP) rates, and apply AI to credit and risk decisions.",
    capabilities: [
      "Intelligent document processing (IDP) with AI extraction",
      "AI-powered workflow automation and straight-through processing",
      "Decisioning engine for credit, fraud, and customer onboarding",
      "Natural language processing for customer communications",
      "Process mining and automation opportunity identification",
      "Integration with existing core banking and CRM systems",
    ],
    useCases: [
      "Automating credit application document review",
      "Straight-through processing for low-risk loan approvals",
      "AI-powered customer complaint routing and resolution",
      "Back-office automation for reconciliation and data entry",
    ],
    industries: ["Commercial Banks", "Rural Banks", "Insurance", "Microfinance", "Payment Companies"],
    faqs: [
      { q: "How is Geniusto different from traditional RPA tools like UiPath or Automation Anywhere?", a: "Geniusto's AI-native approach handles unstructured inputs and exceptions that defeat traditional RPA — making it far more effective for complex banking documents like financial statements, contracts, and KYC documents." },
    ],
  },
  {
    slug: "expleo",
    partnerName: "Expleo",
    logo: "expleo.svg",
    domain: "expleogroup.com",
    category: "Engineering & Digital Transformation",
    headline: "Expleo Engineering & Digital Transformation Services",
    metaTitle: "Expleo Digital Transformation Engineering Partner Philippines | Grover Consult",
    metaDescription: "Grover Consult partners with Expleo to deliver engineering and digital transformation services for Philippine and Indonesian financial institutions — combining consulting, technology, and quality assurance.",
    intro: "Expleo is a global engineering and digital transformation group with deep expertise in regulated industries including banking and financial services. Through the Grover Consult and Expleo partnership, financial institutions in the Philippines and Indonesia gain access to specialist engineering resources, quality assurance capabilities, and large-scale digital transformation delivery expertise.",
    capabilities: [
      "Digital banking platform engineering and development",
      "Quality assurance and testing for critical banking systems",
      "Digital transformation programme management",
      "Cloud migration and platform modernisation",
      "Regulatory technology (RegTech) engineering",
      "Nearshore and offshore delivery for banking IT projects",
    ],
    useCases: [
      "Large-scale digital banking transformation programme delivery",
      "Independent testing and QA for core banking go-lives",
      "Augmenting bank IT teams with specialist engineering resources",
      "Cloud migration of legacy banking applications",
    ],
    industries: ["Commercial Banks", "Universal Banks", "Insurance", "Capital Markets", "Payment Processors"],
    faqs: [
      { q: "How does the Grover Consult and Expleo partnership work?", a: "Grover Consult leads the strategic advisory and client relationship management while leveraging Expleo's engineering scale and specialist capabilities for delivery — giving clients the best of boutique consulting and large-scale execution." },
    ],
  },
  {
    slug: "koreminds",
    partnerName: "Koreminds",
    logo: "koreminds.png",
    domain: "koreminds.ai",
    category: "AI & Intelligent Automation",
    headline: "Koreminds AI & Intelligent Automation for Financial Services",
    metaTitle: "Koreminds AI Implementation Partner Philippines & Indonesia | Grover Consult",
    metaDescription: "Grover Consult partners with Koreminds to deploy AI-driven intelligent automation, conversational AI, and process automation solutions for banks and financial institutions in the Philippines and Indonesia.",
    intro: "Koreminds is a specialist AI and intelligent automation firm delivering enterprise-grade conversational AI, agentic workflows, and intelligent document processing for regulated industries. Through Grover Consult's partnership with Koreminds, banks and financial institutions in the Philippines and Indonesia can rapidly deploy AI agents and automation that reduce operational cost, accelerate customer service, and unlock productivity across the front, middle, and back office.",
    capabilities: [
      "Conversational AI and virtual assistants for banking customer service",
      "Agentic AI workflows for back-office automation",
      "Intelligent document processing and OCR for KYC and lending",
      "AI-powered process automation across front, middle, and back office",
      "Custom LLM fine-tuning and retrieval-augmented generation (RAG) for BFSI",
      "AI governance, model risk, and responsible AI frameworks",
    ],
    useCases: [
      "Deploying AI agents for 24/7 customer service across digital channels",
      "Automating loan document processing and credit memo generation",
      "AI-driven fraud detection and anti-money laundering investigations",
      "Internal employee productivity AI assistants for bank staff",
    ],
    industries: ["Universal Banks", "Commercial Banks", "Rural Banks", "Microfinance", "Insurance", "Fintech"],
    faqs: [
      { q: "How does Koreminds AI ensure data privacy for banks?", a: "Koreminds deploys AI solutions in private cloud or on-premise environments with full data residency and complies with BSP, OJK, and global data protection requirements — ensuring sensitive customer and financial data never leaves the bank's control." },
      { q: "Can Koreminds AI work with our existing core banking and CRM systems?", a: "Yes. Grover Consult and Koreminds integrate AI agents with leading core banking, CRM, and case management platforms via secure APIs — augmenting existing systems without disruptive replacement." },
    ],
  },
  {
    slug: "cbtw",
    partnerName: "CBTW",
    logo: "cbtw.png",
    domain: "cbtw.tech",
    category: "Global Tech Consulting",
    headline: "CBTW Global Tech Consulting & Delivery for BFSI",
    metaTitle: "CBTW Tech Consulting Partner Philippines & Indonesia | Grover Consult",
    metaDescription: "Grover Consult partners with CBTW (Collaboration Betters The World) to deliver global-scale technology consulting, data engineering, and digital product delivery for banks across the Philippines and Indonesia.",
    intro: "CBTW (Collaboration Betters The World) is a global technology consulting and engineering firm with thousands of experts across data, cloud, software, and digital product delivery. Through the Grover Consult and CBTW partnership, financial institutions in the Philippines and Indonesia gain access to global-scale delivery capacity, advanced data and AI engineering, and modern software craftsmanship — combined with Grover Consult's local BFSI domain expertise.",
    capabilities: [
      "Data engineering, lakehouse, and real-time analytics platforms",
      "Cloud-native software development and platform engineering",
      "Digital product design, build, and modernisation",
      "DevSecOps, SRE, and platform reliability engineering",
      "Data and AI strategy with end-to-end implementation",
      "Nearshore and offshore delivery centres for banking IT",
    ],
    useCases: [
      "Building secure data lakehouse platforms for risk and regulatory reporting",
      "Re-platforming legacy banking applications to cloud-native architectures",
      "Designing and shipping new digital banking and wealth products",
      "Establishing DevSecOps and SRE practices in regulated financial environments",
    ],
    industries: ["Universal Banks", "Commercial Banks", "Insurance", "Capital Markets", "Wealth Management", "Fintech"],
    faqs: [
      { q: "What does CBTW bring that Grover Consult doesn't have in-house?", a: "CBTW provides global-scale engineering capacity — thousands of consultants across data, cloud, and software — that complements Grover Consult's boutique advisory and BFSI domain expertise. Together we deliver strategy through to large-scale execution under one accountable partnership." },
      { q: "Can CBTW deliver from the Philippines or do projects run offshore?", a: "Both. The Grover Consult and CBTW partnership combines local Philippine and Indonesian advisory and delivery presence with CBTW's global delivery centres, flexed to each client's data residency, language, and cost requirements." },
    ],
  },
  {
    slug: "finmechanics",
    partnerName: "FinMechanics",
    logo: "finmechanics.png",
    domain: "finmechanics.com",
    category: "Capital Markets & Risk Solutions",
    headline: "FinMechanics Capital Markets, Treasury & Risk Solutions",
    metaTitle: "FinMechanics Implementation Partner Philippines & Indonesia | Grover Consult",
    metaDescription: "Grover Consult is a FinMechanics implementation partner for banks in the Philippines and Indonesia — delivering treasury, capital markets, derivatives, and risk management technology solutions.",
    intro: "FinMechanics is a specialist capital markets and risk technology firm with deep expertise in treasury, derivatives, valuations, and risk management for banks and financial institutions worldwide. Through the Grover Consult and FinMechanics partnership, Philippine and Indonesian banks gain access to FM-Converge and FM-Connect — proven platforms covering trading, treasury, market and credit risk, and regulatory compliance — implemented with local domain expertise.",
    capabilities: [
      "Treasury and capital markets front-to-back office systems",
      "Market risk, credit risk, and counterparty risk management",
      "Derivatives pricing, valuations, and XVA",
      "IFRS 9 expected credit loss and impairment modelling",
      "FRTB, Basel, and regulatory capital reporting",
      "Asset-liability management (ALM) and liquidity risk",
    ],
    useCases: [
      "Replacing legacy treasury and trading systems with modern integrated platforms",
      "Implementing IFRS 9 ECL engines aligned with BSP and OJK requirements",
      "Building enterprise-wide risk management for universal banks",
      "Modernising ALM and liquidity risk reporting for ICAAP and ILAAP",
    ],
    industries: ["Universal Banks", "Investment Banks", "Capital Markets", "Treasury Operations", "Insurance"],
    faqs: [
      { q: "Is FinMechanics suitable for mid-size Philippine banks or only large universal banks?", a: "FinMechanics platforms are modular and scale from focused treasury or risk deployments at mid-size banks through to enterprise-wide capital markets and risk transformations at large universal banks. Grover Consult right-sizes the implementation to each client's complexity and budget." },
      { q: "Does FinMechanics support BSP regulatory reporting requirements?", a: "Yes. Grover Consult configures FinMechanics' risk and regulatory modules to meet BSP requirements including IFRS 9, Basel capital, large exposures, and liquidity reporting — alongside global standards like FRTB where applicable." },
    ],
  },
];

export const servicePages: ServicePage[] = [
  {
    slug: "digital-transformation-consulting",
    title: "Digital Transformation Consulting",
    metaTitle: "Digital Transformation Consulting for Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult provides digital transformation consulting for banks and financial institutions in the Philippines and Indonesia — strategy, roadmap, vendor selection, and implementation leadership.",
    headline: "Digital Transformation Consulting for BFSI in Southeast Asia",
    intro: "Grover Consult is Southeast Asia's specialist boutique consulting firm for digital transformation in banking, financial services, and insurance (BFSI). With over 35 years of combined delivery experience, our team guides financial institutions through every stage of their digital transformation journey — from strategy and roadmap to vendor selection, implementation, and change management.",
    benefits: [
      { title: "Vendor-Neutral Strategy", description: "We assess your specific context and recommend the right technology stack from our ecosystem of 18 vetted solution partners — not what any single vendor tells you." },
      { title: "BFSI Specialisation", description: "Unlike generalist firms, Grover Consult works exclusively in banking, insurance, and finance — bringing deep regulatory knowledge (BSP, OJK) and industry-specific delivery experience." },
      { title: "End-to-End Delivery", description: "We don't stop at the strategy deck. Our team delivers the full implementation — from requirements and vendor contracting through go-live and hypercare." },
      { title: "Change Management", description: "Technology alone doesn't drive transformation. Our change management practice ensures your people adopt new systems and ways of working." },
    ],
    deliverables: [
      "Digital Transformation Strategy and Roadmap",
      "Technology Architecture Blueprint",
      "Vendor Evaluation and Selection Support",
      "Business Case and ROI Modelling",
      "Programme Governance and Delivery Management",
      "Post-implementation Review and Optimisation",
    ],
    faqs: [
      { q: "What types of banks does Grover Consult work with in the Philippines?", a: "We work with universal banks, commercial banks, thrift banks, rural banks, and digital banks (neobanks) across all asset size segments — from the largest universal banks to community rural banks." },
      { q: "Does Grover Consult work with insurance companies in the Philippines?", a: "Yes. While our primary focus is banking, we also work with insurance companies and other financial service providers undertaking digital transformation." },
      { q: "How is Grover Consult different from the Big 4 consulting firms?", a: "Our boutique model means your project gets senior, specialised BFSI expertise — not junior consultants supervised from afar. We move faster, cost less, and stay accountable through go-live and beyond." },
    ],
  },
  {
    slug: "core-banking-implementation",
    title: "Core Banking Implementation",
    metaTitle: "Core Banking Implementation Consultant Philippines Indonesia | Grover Consult",
    metaDescription: "Grover Consult leads core banking implementation projects for Philippine and Indonesian banks — from legacy migration and vendor selection through go-live management and post-implementation support.",
    headline: "Core Banking Implementation for Philippine & Indonesian Banks",
    intro: "Core banking replacement is one of the most complex, high-stakes technology initiatives a bank can undertake. Grover Consult specialises in leading core banking system (CBS) transformations — providing independent advisory, implementation management, and technical delivery support to ensure banks achieve a successful go-live without disruption to operations or customers.",
    benefits: [
      { title: "Vendor-Independent Advisory", description: "We advise on CBS platform selection (TCS BaNCS, Temenos, Finacle, Oracle FLEXCUBE) based on your bank's specific requirements — not vendor relationships." },
      { title: "Migration Expertise", description: "Our team has deep experience in the most complex part of any CBS transformation: data migration. We manage data mapping, cleansing, and parallel run governance to protect data integrity." },
      { title: "Regulatory Configuration", description: "We ensure every CBS implementation is configured for BSP (Philippines) and OJK (Indonesia) regulatory reporting from day one." },
      { title: "Risk Management", description: "Core banking go-live is a critical risk event. Our programme governance framework includes robust testing management, cutover planning, and hypercare to protect operations." },
    ],
    deliverables: [
      "Core Banking System Selection Assessment and RFP Management",
      "Functional Requirements and Business Process Design",
      "Data Migration Strategy and Execution",
      "System Integration Architecture and Testing",
      "Go-Live Readiness Assessment and Cutover Management",
      "Hypercare and Post-Implementation Review",
    ],
    faqs: [
      { q: "Which core banking systems does Grover Consult have implementation experience with?", a: "Our team has hands-on implementation experience with TCS BaNCS, Temenos T24/Transact, Oracle FLEXCUBE, and selected regional CBS platforms. We are an authorized TCS BaNCS implementation partner." },
      { q: "How do you manage the risk of a core banking go-live?", a: "Our go-live management methodology includes: a 12-week parallel run minimum, mock cutover rehearsals, a command centre structure, a detailed cutover runbook, and a defined go/no-go decision framework with executive sign-off." },
      { q: "Can Grover Consult help with BSP/OJK approval for a new core banking system?", a: "Yes. We support banks in preparing the technology risk assessment documentation and regulatory notification required by BSP and OJK when implementing a new core banking system." },
    ],
  },
  {
    slug: "sales-enablement-consulting",
    title: "Sales Enablement Consulting",
    metaTitle: "Sales Enablement Consulting for Banks Philippines | Grover Consult",
    metaDescription: "Grover Consult delivers sales enablement consulting for financial institutions in the Philippines and Indonesia — building high-performance sales teams, CRM optimisation, and digital sales channels.",
    headline: "Sales Enablement Consulting for Financial Institutions",
    intro: "Grover Consult's sales enablement practice helps banks and financial institutions build the sales capabilities, tools, and culture needed to compete in a digital-first market. From CRM deployment and sales process design to digital prospecting tools and performance management frameworks, we equip BFSI sales teams to drive sustainable revenue growth.",
    benefits: [
      { title: "Sales Process Redesign", description: "We analyse your current sales funnel from lead to close and redesign it to reduce friction, increase conversion rates, and shorten the sales cycle." },
      { title: "CRM Implementation & Adoption", description: "CRM success depends on adoption. We manage both the technology deployment and the change programme needed to make CRM a daily sales tool — not a reporting burden." },
      { title: "Digital Prospecting Tools", description: "We deploy digital prospecting tools, lead scoring models, and social selling frameworks that help relationship managers find and engage prospects more efficiently." },
      { title: "Sales Performance Management", description: "We build KPI frameworks, sales dashboards, and coaching programmes that give sales leaders real-time visibility and a structured approach to improving team performance." },
    ],
    deliverables: [
      "Sales Process Assessment and Redesign",
      "CRM Platform Selection and Implementation (Salesforce, Dynamics 365, Pipedrive)",
      "Sales Playbook Development",
      "Digital Prospecting Tools and Lead Management",
      "Sales Performance Dashboard and KPI Framework",
      "Sales Team Training and Change Management",
    ],
    faqs: [
      { q: "Does Grover Consult implement Salesforce for banks in the Philippines?", a: "Yes. We have experience implementing Salesforce Financial Services Cloud for Philippine banks, configured for BSP-regulated products and local market requirements." },
      { q: "How long does a sales enablement engagement typically take?", a: "A focused sales enablement engagement — covering process redesign, CRM implementation, and training — typically takes 4–9 months depending on scope and bank size." },
    ],
  },
  {
    slug: "system-integration-implementation",
    title: "System Integration & Implementation",
    metaTitle: "Banking System Integration Consultant Philippines Indonesia | Grover Consult",
    metaDescription: "Grover Consult provides system integration and implementation services for banks in the Philippines and Indonesia — connecting core banking, digital channels, payment schemes, and third-party systems.",
    headline: "Banking System Integration & Implementation in Southeast Asia",
    intro: "Modern banking architecture requires dozens of systems to work seamlessly together — core banking, digital channels, payment schemes, AML, CRM, treasury, and more. Grover Consult's system integration practice designs and delivers the integration architecture that connects your banking technology ecosystem, using API-first approaches and enterprise integration patterns proven in BFSI environments.",
    benefits: [
      { title: "API-First Integration Architecture", description: "We design integration architectures built on REST APIs, event streaming, and microservices — enabling real-time data flow and resilient system connectivity." },
      { title: "Payment Scheme Connectivity", description: "We connect banks to Philippine payment schemes (InstaPay, PESONet, PESOPay) and Indonesian schemes (BI-FAST, RTGS) — handling the technical integration and regulatory compliance requirements." },
      { title: "Legacy System Integration", description: "We specialise in integrating modern digital systems with legacy core banking environments — using adapter patterns and middleware to preserve investments in existing infrastructure." },
      { title: "End-to-End Testing", description: "Integration projects fail when testing is insufficient. We run comprehensive end-to-end integration testing covering all connected systems before go-live." },
    ],
    deliverables: [
      "Integration Architecture Design and Blueprint",
      "API Specification and Interface Control Documents",
      "Middleware and ESB Configuration",
      "Payment Scheme Technical Integration",
      "System Integration Testing (SIT) Management",
      "Production Deployment and Monitoring Setup",
    ],
    faqs: [
      { q: "Can Grover Consult integrate our new digital banking app with our legacy core banking system?", a: "Yes. This is one of our most common engagements. We use API gateway and middleware approaches to bridge modern digital channels with legacy CBS platforms, avoiding a full CBS replacement in the near term." },
      { q: "Do you handle InstaPay and PESONet integration for Philippine banks?", a: "Yes. We have experience connecting banks to BSP-regulated payment schemes including InstaPay and PESONet via the certified BSP payment scheme technical providers." },
    ],
  },
];

export const countryPages = [
  {
    slug: "philippines",
    country: "Philippines",
    flag: "🇵🇭",
    metaTitle: "Digital Transformation Consulting Philippines Banking | Grover Consult",
    metaDescription: "Grover Consult is the Philippines' specialist BFSI digital transformation consulting firm — serving Philippine banks, rural banks, thrift banks, and digital banks across all transformation programmes.",
    headline: "BFSI Digital Transformation Consulting in the Philippines",
    intro: "Grover Consult has deep roots in the Philippine banking market, with extensive experience working alongside BSP-regulated institutions from universal banks to rural banks and digital banks. Our team understands the Philippine regulatory landscape, local market dynamics, and the technology challenges facing Philippine financial institutions — making us the trusted implementation partner for banks undertaking digital transformation in the Philippines.",
    context: "The Philippine banking sector is undergoing accelerated digital transformation driven by BSP's Digital Payments Transformation Roadmap, the Open Finance Framework, and rising competition from digital banks and fintech players. Grover Consult helps Philippine banks navigate this transformation with pragmatic, expert advisory and delivery support.",
    keyProjects: [
      "Core banking system replacement for Philippine commercial and thrift banks",
      "Digital onboarding and e-KYC implementation for BSP compliance",
      "InstaPay and PESONet integration and payment scheme connectivity",
      "Open Finance API framework deployment (BSP Circular 1153)",
      "AML/AMLA compliance platform implementation for AMLC reporting",
    ],
    regulatoryContext: "We are deeply familiar with BSP regulations including the Manual of Regulations for Banks (MORB), Circular 982 (Technology Risk Management), Circular 1033 (Digital Banking), Circular 1153 (Open Finance), and AMLA/AMLC reporting requirements.",
  },
  {
    slug: "indonesia",
    country: "Indonesia",
    flag: "🇮🇩",
    metaTitle: "Digital Transformation Consulting Indonesia Banking | Grover Consult",
    metaDescription: "Grover Consult supports Indonesian banks and financial institutions with digital transformation consulting — core banking, digital channels, payments, and compliance across OJK-regulated environments.",
    headline: "BFSI Digital Transformation Consulting in Indonesia",
    intro: "Indonesia's banking sector is one of Southeast Asia's largest and fastest-growing, with OJK driving a comprehensive digital banking transformation agenda. Grover Consult brings proven BFSI transformation expertise to Indonesian banks, helping them respond to the competitive challenge of digital-native banks, implement OJK regulatory requirements, and modernise technology infrastructure.",
    context: "Indonesia's financial sector transformation is accelerating, driven by OJK's Digital Transformation Blueprint for Banking, the BI-FAST instant payment rollout, and the rise of digital banks targeting Indonesia's large underbanked population. Grover Consult helps established banks and digital banks compete effectively in this rapidly evolving market.",
    keyProjects: [
      "Core banking transformation for Indonesian commercial banks",
      "BI-FAST real-time payment scheme integration and connectivity",
      "OJK-compliant digital banking platform implementation",
      "AML transaction monitoring and PPATK reporting implementation",
      "Digital lending platform for underbanked Indonesian segments",
    ],
    regulatoryContext: "We understand the OJK regulatory framework including POJK 12/2021 (Digital Banking), POJK 38/2016 (IT Risk Management), OJK SNAP API standards, PPATK AML reporting, and the Indonesian Personal Data Protection (PDP) Law.",
  },
];
